### ISSUE TITLE
integrated error

### ISSUE THREAD

**Issue by linking12** [oktadeveloper/okta-spring-boot-oauth-example#5]
when I integrated okta with spring boot oauth，It response me 404 ；
https://dev-199105-admin.okta.com/error/404?fromURI=%2Foauth2%2Fdefault%2Fv1%2Fauthorize%3Fclient_id%3D0oaz4m4mcM8skClBb356%26redirect_uri%3Dhttp%3A%2F%2Flocalhost%3A8070%2Fsignin%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520email%26state%3DLwup6F

![image](https://user-images.githubusercontent.com/4882172/61677559-a5044000-ad32-11e9-9bb3-10a63bd25969.png)

Okta Console:
![image](https://user-images.githubusercontent.com/4882172/61677749-47bcbe80-ad33-11e9-8158-907d5f1b767e.png)

Spring Boot Yml ：

```
security:
   oauth2:
      client:
         clientId: 0oaz4m4mcM8skClBb356
         clientSecret: k7m8bAAiIcDYRpEzmhcspvjSXyQRAxh-ZkCk-nuI
         accessTokenUri: https://dev-199105-admin.okta.com/oauth2/default/v1/token
         userAuthorizationUri: https://dev-199105-admin.okta.com/oauth2/default/v1/authorize
         scope: openid profile email
      sso:
         loginPath: /signin
      resource:
         userInfoUri: https://dev-199105-admin.okta.com/oauth2/default/v1/userinfo
```

POM:
```
<dependency>
 <groupId>org.springframework.security.oauth.boot</groupId>
  <artifactId>spring-security-oauth2-autoconfigure</artifactId>
  <version>2.0.0.RELEASE</version>
<dependency>
```

**Comment by mraible** [comment]
Remove “-admin” from the URL and it should work.

**Comment by linking12** [comment]
@mraible 
I know you mean, must use okta proview, but it is wrong; 
the error is :
![image](https://user-images.githubusercontent.com/4882172/61681309-996b4600-ad3f-11e9-9fe8-aa5b3f3fc395.png)


okta console by oktapreview:
![image](https://user-images.githubusercontent.com/4882172/61681232-51e4ba00-ad3f-11e9-9ac4-3c188f03710c.png)
yml:
```
security:
   oauth2:
      client:
         clientId: 0oamdu8o9dD9cYHCY0h7
         clientSecret: 8k8zTTULi6qTuncjBazyQE4nQHXftqRsvu7sr3CJ
         accessTokenUri: https://binance.oktapreview.com/oauth2/default/v1/token
         userAuthorizationUri: https://binance.oktapreview.com/oauth2/default/v1/authorize
         client-authentication-scheme: form
      sso:
         loginPath: /signin
      resource:
         userInfoUri: https://binance.oktapreview.com/oauth2/default/v1/userinfo
```
